<p>
	Quando for chamar tal método (que vai lançar uma exceção <em>Throw</em> quando falhar na execução), deverá utilizar o <em>Try/Catch</em> para que ele o código que for chamá-lo possa tomar conta dele (com o <em>Catch</em>).
</p>
<p>
	Tudo isso deve ser feito, pois o compilador verificara todas as classes de “exceções checadas”, EXCETO o <em>RuntimeExceptions</em> (exceções lançadas no <em>Throw</em>), que são consideradas um tipo especial de exceção. 
</p>